species:
  - alias: "Human"
    reference: "hg38"
  - alias: "Mouse"
    reference: "mm10"
  - alias: "Fly"
    reference: "dm6"
  - alias: "Arabidopsis"
    reference: "TAIR10"
  - alias: "Escherichia coli"
    reference: "MG1655"
  - alias: "Bos taurus"
    reference: "BosTau9"
  - alias: "Horse"
    reference: "equcab3"
